# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-case-conflict
    -   id: mixed-line-ending
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix']
    -   id: check-merge-conflict
    -   id: check-docstring-first

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
      args:
        - --line-length=100
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args:
        - --max-line-length=100
        - --ignore=E203, E266, E501, W503
        - --max-complexity=18
        - --select=B,C,E,F,W,T4,B9

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args:
        - --line-length=100

- repo: https://github.com/myint/autoflake
  rev: v2.2.0
  hooks:
    - id: autoflake
      args:
        - --in-place
        - --remove-unused-variables
        - --remove-all-unused-imports
# - repo: https://github.com/econchick/interrogate
#   rev: 1.5.0
#   hooks:
#     - id: interrogate
#       args: [-vv, -i]
